import "server-only";
import { prisma } from "@/lib/prisma";

/**
 * Trip clustering.
 *
 * A trip is a sequence of consecutive flights bounded by EITHER:
 *   (a) a gap of > MAX_GAP_DAYS to the next flight, OR
 *   (b) the most recent flight returning to HOME_AIRPORT.
 *
 * `HOME_AIRPORT_IATA` env var pins the home; default "VNO".
 *
 * The algorithm is idempotent: re-running re-derives clusters from scratch
 * after first NULLing out `tripId` on user flights and deleting auto-generated
 * trips.
 */

const MAX_GAP_DAYS = 21;

type Leg = {
  id: string;
  date: Date;
  firstSeenUtc: Date | null;
  depIata: string | null;
  arrIata: string | null;
  arrCity: string | null;
  arrLat: number;
  arrLon: number;
  depLat: number;
  depLon: number;
};

export async function rebuildTripsForOwner(userId: string): Promise<{
  trips: number;
  flights: number;
}> {
  const home = (process.env.HOME_AIRPORT_IATA ?? "VNO").toUpperCase();

  // Detach all flights from auto-generated trips, then delete those trips.
  const oldTrips = await prisma.trip.findMany({
    where: { userId, autoGenerated: true },
    select: { id: true },
  });
  await prisma.flight.updateMany({
    where: { userId, tripId: { in: oldTrips.map((t) => t.id) } },
    data: { tripId: null },
  });
  await prisma.trip.deleteMany({ where: { userId, autoGenerated: true } });

  const flights = await prisma.flight.findMany({
    where: {
      userId,
      resolutionStatus: { in: ["resolved", "no_coverage"] },
    },
    orderBy: [{ date: "asc" }, { firstSeenUtc: "asc" }, { createdAt: "asc" }],
    include: { depAirport: true, arrAirport: true },
  });
  if (flights.length === 0) return { trips: 0, flights: 0 };

  const legs: Leg[] = flights.map((f) => ({
    id: f.id,
    date: f.date,
    firstSeenUtc: f.firstSeenUtc,
    depIata: f.depAirport.iata,
    arrIata: f.arrAirport.iata,
    arrCity: f.arrAirport.municipality ?? f.arrAirport.name,
    arrLat: f.arrAirport.latitude,
    arrLon: f.arrAirport.longitude,
    depLat: f.depAirport.latitude,
    depLon: f.depAirport.longitude,
  }));

  // Walk and accumulate clusters.
  const clusters: Leg[][] = [];
  let current: Leg[] = [];
  for (const leg of legs) {
    if (current.length === 0) {
      current.push(leg);
      continue;
    }
    const previous = current[current.length - 1];
    const dayGap = daysBetween(previous.date, leg.date);
    const previousReturnedHome = previous.arrIata === home;

    if (dayGap > MAX_GAP_DAYS || previousReturnedHome) {
      clusters.push(current);
      current = [leg];
    } else {
      current.push(leg);
    }
  }
  if (current.length > 0) clusters.push(current);

  // Persist.
  let createdTrips = 0;
  let attachedFlights = 0;
  for (const cluster of clusters) {
    if (cluster.length === 0) continue;
    const first = cluster[0];
    const last = cluster[cluster.length - 1];
    const label = makeTripLabel(cluster, home);
    const trip = await prisma.trip.create({
      data: {
        userId,
        label,
        startUtc: first.firstSeenUtc ?? first.date,
        endUtc: last.firstSeenUtc ?? last.date,
        homeAirport: home,
        autoGenerated: true,
      },
    });
    await prisma.flight.updateMany({
      where: { id: { in: cluster.map((l) => l.id) } },
      data: { tripId: trip.id },
    });
    createdTrips += 1;
    attachedFlights += cluster.length;
  }

  return { trips: createdTrips, flights: attachedFlights };
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

function daysBetween(a: Date, b: Date): number {
  return Math.abs(Math.round((b.getTime() - a.getTime()) / 86_400_000));
}

function makeTripLabel(cluster: Leg[], home: string): string {
  // Label by the farthest-from-home airport reached during the trip.
  // Single-leg trips with home as departure get the destination city.
  // Multi-leg trips get the deepest non-home airport.

  // Try to find a "home base" coord from any home airport in the cluster.
  const homeLeg = cluster.find((l) => l.depIata === home || l.arrIata === home);
  const homeLat = homeLeg?.depIata === home ? homeLeg.depLat : homeLeg?.arrLat ?? null;
  const homeLon = homeLeg?.depIata === home ? homeLeg.depLon : homeLeg?.arrLon ?? null;

  // Candidate destinations are the arrIata values of every leg (and dep on the
  // way back) that aren't home.
  type Candidate = { iata: string | null; city: string | null; lat: number; lon: number };
  const cands: Candidate[] = [];
  for (const leg of cluster) {
    if (leg.arrIata && leg.arrIata !== home) {
      cands.push({ iata: leg.arrIata, city: leg.arrCity, lat: leg.arrLat, lon: leg.arrLon });
    }
    if (leg.depIata && leg.depIata !== home) {
      cands.push({ iata: leg.depIata, city: leg.arrCity, lat: leg.depLat, lon: leg.depLon });
    }
  }
  if (cands.length === 0) {
    return `Trip ${cluster[0].date.toISOString().slice(0, 10)}`;
  }

  let furthest = cands[0];
  if (homeLat !== null && homeLon !== null) {
    let bestDist = haversineKm(homeLat, homeLon, furthest.lat, furthest.lon);
    for (const c of cands) {
      const d = haversineKm(homeLat, homeLon, c.lat, c.lon);
      if (d > bestDist) {
        bestDist = d;
        furthest = c;
      }
    }
  }
  const year = cluster[0].date.getUTCFullYear();
  return `${furthest.city ?? furthest.iata ?? "Trip"} ${year}`;
}

function haversineKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371.0088;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const phi1 = toRad(lat1);
  const phi2 = toRad(lat2);
  const dphi = toRad(lat2 - lat1);
  const dlam = toRad(lon2 - lon1);
  const a =
    Math.sin(dphi / 2) ** 2 + Math.cos(phi1) * Math.cos(phi2) * Math.sin(dlam / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}
