-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- CreateEnum
CREATE TYPE "ResolutionStatus" AS ENUM ('pending', 'resolved', 'no_coverage', 'ambiguous', 'failed');

-- CreateEnum
CREATE TYPE "FlightSource" AS ENUM ('manual', 'email', 'imported');

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "name" TEXT,
    "email" TEXT NOT NULL,
    "emailVerified" TIMESTAMP(3),
    "image" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Account" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "refresh_token" TEXT,
    "access_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT,

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL,
    "sessionToken" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VerificationToken" (
    "identifier" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL
);

-- CreateTable
CREATE TABLE "airports" (
    "id" TEXT NOT NULL,
    "icao" VARCHAR(4),
    "iata" VARCHAR(3),
    "name" TEXT NOT NULL,
    "municipality" TEXT,
    "isoCountry" VARCHAR(2),
    "latitude" DOUBLE PRECISION NOT NULL,
    "longitude" DOUBLE PRECISION NOT NULL,
    "elevationFt" INTEGER,
    "type" TEXT,

    CONSTRAINT "airports_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "airlines" (
    "id" TEXT NOT NULL,
    "icao" VARCHAR(3),
    "iata" VARCHAR(2),
    "name" TEXT NOT NULL,
    "callsign" TEXT,
    "country" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "airlines_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "aircraft_types" (
    "id" TEXT NOT NULL,
    "icaoCode" VARCHAR(4) NOT NULL,
    "manufacturer" TEXT,
    "model" TEXT NOT NULL,
    "seatsTypical" INTEGER,
    "fuelBurnPerHourKg" DOUBLE PRECISION,

    CONSTRAINT "aircraft_types_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "aircraft" (
    "id" TEXT NOT NULL,
    "icao24" VARCHAR(6) NOT NULL,
    "registration" TEXT,
    "typeCode" VARCHAR(4),
    "model" TEXT,
    "operator" TEXT,
    "operatorIcao" VARCHAR(3),
    "yearBuilt" INTEGER,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "aircraft_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "flights" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "callsign" TEXT,
    "registration" TEXT,
    "icao24" VARCHAR(6),
    "depAirportId" TEXT NOT NULL,
    "arrAirportId" TEXT NOT NULL,
    "airlineId" TEXT,
    "aircraftTypeId" TEXT,
    "aircraftId" TEXT,
    "tripId" TEXT,
    "seat" TEXT,
    "notes" TEXT,
    "firstSeenUtc" TIMESTAMP(3),
    "lastSeenUtc" TIMESTAMP(3),
    "distanceKm" DOUBLE PRECISION,
    "durationMin" INTEGER,
    "co2Kg" DOUBLE PRECISION,
    "resolutionStatus" "ResolutionStatus" NOT NULL DEFAULT 'pending',
    "resolutionError" TEXT,
    "resolutionAttempts" INTEGER NOT NULL DEFAULT 0,
    "resolvedAt" TIMESTAMP(3),
    "source" "FlightSource" NOT NULL DEFAULT 'manual',
    "sourceEmailId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "flights_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tracks" (
    "id" TEXT NOT NULL,
    "flightId" TEXT NOT NULL,
    "waypoints" JSONB NOT NULL,
    "gaps" JSONB,
    "greatCircle" JSONB,
    "source" TEXT NOT NULL DEFAULT 'opensky',
    "pointCount" INTEGER NOT NULL DEFAULT 0,
    "fetchedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tracks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "trips" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "label" TEXT,
    "startUtc" TIMESTAMP(3) NOT NULL,
    "endUtc" TIMESTAMP(3) NOT NULL,
    "homeAirport" TEXT,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "trips_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "email_imports" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "messageId" TEXT NOT NULL,
    "threadId" TEXT,
    "subject" TEXT,
    "fromAddr" TEXT,
    "receivedAt" TIMESTAMP(3),
    "parsedFlightsCount" INTEGER NOT NULL DEFAULT 0,
    "confidence" TEXT,
    "status" TEXT NOT NULL DEFAULT 'parsed',
    "rawExcerpt" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "email_imports_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "opensky_credits" (
    "id" BIGSERIAL NOT NULL,
    "day" TIMESTAMP(3) NOT NULL,
    "endpoint" TEXT NOT NULL,
    "credits" INTEGER NOT NULL,
    "requestId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "opensky_credits_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");

-- CreateIndex
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token");

-- CreateIndex
CREATE UNIQUE INDEX "airports_icao_key" ON "airports"("icao");

-- CreateIndex
CREATE INDEX "airports_iata_idx" ON "airports"("iata");

-- CreateIndex
CREATE INDEX "airports_isoCountry_idx" ON "airports"("isoCountry");

-- CreateIndex
CREATE INDEX "airports_latitude_longitude_idx" ON "airports"("latitude", "longitude");

-- CreateIndex
CREATE UNIQUE INDEX "airlines_icao_key" ON "airlines"("icao");

-- CreateIndex
CREATE INDEX "airlines_iata_idx" ON "airlines"("iata");

-- CreateIndex
CREATE UNIQUE INDEX "aircraft_types_icaoCode_key" ON "aircraft_types"("icaoCode");

-- CreateIndex
CREATE UNIQUE INDEX "aircraft_icao24_key" ON "aircraft"("icao24");

-- CreateIndex
CREATE INDEX "aircraft_registration_idx" ON "aircraft"("registration");

-- CreateIndex
CREATE INDEX "aircraft_typeCode_idx" ON "aircraft"("typeCode");

-- CreateIndex
CREATE INDEX "flights_userId_date_idx" ON "flights"("userId", "date" DESC);

-- CreateIndex
CREATE INDEX "flights_date_idx" ON "flights"("date");

-- CreateIndex
CREATE INDEX "flights_icao24_idx" ON "flights"("icao24");

-- CreateIndex
CREATE INDEX "flights_callsign_idx" ON "flights"("callsign");

-- CreateIndex
CREATE INDEX "flights_resolutionStatus_idx" ON "flights"("resolutionStatus");

-- CreateIndex
CREATE UNIQUE INDEX "tracks_flightId_key" ON "tracks"("flightId");

-- CreateIndex
CREATE INDEX "tracks_flightId_idx" ON "tracks"("flightId");

-- CreateIndex
CREATE INDEX "trips_userId_startUtc_idx" ON "trips"("userId", "startUtc");

-- CreateIndex
CREATE UNIQUE INDEX "email_imports_messageId_key" ON "email_imports"("messageId");

-- CreateIndex
CREATE INDEX "email_imports_userId_idx" ON "email_imports"("userId");

-- CreateIndex
CREATE INDEX "email_imports_messageId_idx" ON "email_imports"("messageId");

-- CreateIndex
CREATE INDEX "opensky_credits_day_idx" ON "opensky_credits"("day");

-- AddForeignKey
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "aircraft" ADD CONSTRAINT "aircraft_typeCode_fkey" FOREIGN KEY ("typeCode") REFERENCES "aircraft_types"("icaoCode") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "flights" ADD CONSTRAINT "flights_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "flights" ADD CONSTRAINT "flights_depAirportId_fkey" FOREIGN KEY ("depAirportId") REFERENCES "airports"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "flights" ADD CONSTRAINT "flights_arrAirportId_fkey" FOREIGN KEY ("arrAirportId") REFERENCES "airports"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "flights" ADD CONSTRAINT "flights_airlineId_fkey" FOREIGN KEY ("airlineId") REFERENCES "airlines"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "flights" ADD CONSTRAINT "flights_aircraftTypeId_fkey" FOREIGN KEY ("aircraftTypeId") REFERENCES "aircraft_types"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "flights" ADD CONSTRAINT "flights_aircraftId_fkey" FOREIGN KEY ("aircraftId") REFERENCES "aircraft"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "flights" ADD CONSTRAINT "flights_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "trips"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tracks" ADD CONSTRAINT "tracks_flightId_fkey" FOREIGN KEY ("flightId") REFERENCES "flights"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trips" ADD CONSTRAINT "trips_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "email_imports" ADD CONSTRAINT "email_imports_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
